apiVersion: v1 
kind: Service
metadata:
  name: autoscale-app-svc
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCPd
  selector:
    app: autoscale
    env: training
  type: LoadBalancer  
